Algoritmo "semnome"
// Disciplina   : Programação
// Professor   : Richard Brosler 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2022
Var
// Seção de Declarações das variáveis 
    cnt: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para cnt de 0 ate 10 faca
   escreval("5 x ",cnt,"=",5*cnt)
    fimpara

Fimalgoritmo